   name: Deploy to Render

   on:
     push:
       branches:
         - main

   jobs:
     test-and-deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Validacion previa
         run: |
           date
           hostname
           pwd
           ls -l
           find . 

       - name: Checkout code
         uses: actions/checkout@v3

       - name: Validacion posterior
         run: find . 

       - name: Deploy to Render
         if: success()
         run: |
           curl -X POST "https://api.render.com/deploy/srv-csldbbjqf0us738rhsig?key=rnd_lwEgnWjYDIVDelNLMufjsHj3T6xc" -H "Content-Type: application/json" -d '{}'

           
